services:
  devcontainer:
    build:
      args:
        USERNAME: ${USERNAME}
      context: .
    command: sleep infinity
    pull_policy: never
    user: ${USERNAME}
    volumes:
      - type: bind
        source: ..
        target: /workspaces/${COMPOSE_PROJECT_NAME}
